### ISSUE TITLE
Addition Request - Paper on Improving Reasoning of Large Language Models with Alignment

### ISSUE THREAD

**Issue by Wangpeiyi9979** [GaryYufei/AlignLLMHumanSurvey#3]
Hi, thanks for your excellent survey.

We recently proposed a new **ranking strategy** to align large language models (LLMs) to enhance their **reasoning ability**.
We also delve deeply into recent ranking-based alignment methods, such as DPO, RRHF, and PRO, and provide some analyses.

Here are the details of our work:

Title: Making Large Language Models Better Reasoners with Alignment
Link: https://arxiv.org/pdf/2309.02144.pdf

We kindly request that you consider adding our work to this repository and the survey. 
Thank you for your time and consideration. 😊

**Comment by GaryYufei** [comment]
Thanks for sharing this great work with us. I have just added your paper into repo (see https://github.com/GaryYufei/AlignLLMHumanSurvey#rank-based-training), which will be incorporated into our next version of this survey!

**Comment by Wangpeiyi9979** [comment]
Thanks!
